### ISSUE TITLE
call gcalcli from 57_GCALVIEW

### ISSUE THREAD

**Issue by hst59** [mumpitzstuff/fhem-GCALVIEW#2]
pi@fhemraspi01:/opt/fhem $ gcalcli --version
gcalcli v4.0.3 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)

gcalview 08.03.2019

gcalcli list .........
line 310: option: --configFolder changed to --config-folder

gcalcli agenda
line 364,368: option: --detail_all changed to -- details all
                                 --configFolder deleted - not option of agenda

this seems to be ok, but get an "invalid gcalcli output" for each calendar entry with correct values.
one is a one day entry, second one is a two day entry, both start end ends with zero time 00:00, one is with reminder the other one w/o reminder
hope you have an idea. I will have a look to it next days.

regards
hst59

**Comment by mumpitzstuff** [comment]
Please do not use gcalcli 4.x! I have never tested one of these versions. Please try to use 3.4.0. But i will try to install the new version to see what is needed to get it working too.

**Comment by mumpitzstuff** [comment]
[https://forum.fhem.de/index.php/topic,77502.msg920484.html#msg920484](url)

Can you test this version please? I tested it with gcalcli 4.0.4. Be sure that you install gcalcli for python3 and NOT for python2 (uninstall the python2 version). I had some utf8 problems because gcalcli was installed for python2.

**Comment by mumpitzstuff** [comment]
Latest version is tested with gcalcli 4.0.4.
